// <auto-generated />
// Responsabilidad del archivo: conserva los metadatos EF Core de la corrección de calendario y triggers.
// Relación en el sistema: permite a EF Core identificar y aplicar esta migración incremental.
using System;
using DotNetTestMundial.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DotNetTestMundial.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(TournamentDbContext))]
    [Migration("20260913025558_PreventSameDayMatchesAndSupportTriggers")]
    partial class PreventSameDayMatchesAndSupportTriggers
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.19")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DotNetTestMundial.Domain.Entities.Goal", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("MatchId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Minute")
                        .HasColumnType("int");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("MatchId");

                    b.HasIndex("PlayerId", "TeamId");

                    b.ToTable("Goals", null, t =>
                        {
                            t.HasCheckConstraint("CK_Goals_Minute", "[Minute] >= 1 AND [Minute] <= 120");
                        });
                });

            modelBuilder.Entity("DotNetTestMundial.Domain.Entities.Match", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("AwayScore")
                        .HasColumnType("int");

                    b.Property<Guid>("AwayTeamId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("HomeScore")
                        .HasColumnType("int");

                    b.Property<Guid>("HomeTeamId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ScheduledAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AwayTeamId");

                    b.HasIndex("HomeTeamId");

                    b.HasIndex("ScheduledAt");

                    b.HasIndex("Status", "ScheduledAt");

                    b.ToTable("Matches", null, t =>
                        {
                            t.HasCheckConstraint("CK_Matches_DifferentTeams", "[HomeTeamId] <> [AwayTeamId]");

                            t.HasCheckConstraint("CK_Matches_StateAndScore", "([Status] = 2 AND [HomeScore] IS NOT NULL AND [AwayScore] IS NOT NULL AND [HomeScore] >= 0 AND [AwayScore] >= 0) OR ([Status] IN (1, 3) AND [HomeScore] IS NULL AND [AwayScore] IS NULL)");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("DotNetTestMundial.Domain.Entities.Player", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("JerseyNumber")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TeamId");

                    b.HasIndex("TeamId", "JerseyNumber")
                        .IsUnique()
                        .HasDatabaseName("UX_Players_TeamId_JerseyNumber");

                    b.ToTable("Players", null, t =>
                        {
                            t.HasCheckConstraint("CK_Players_JerseyNumber", "[JerseyNumber] > 0");
                        });
                });

            modelBuilder.Entity("DotNetTestMundial.Domain.Entities.Team", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("UX_Teams_Name");

                    b.HasIndex("ShortName")
                        .IsUnique()
                        .HasDatabaseName("UX_Teams_ShortName");

                    b.ToTable("Teams", (string)null);
                });

            modelBuilder.Entity("DotNetTestMundial.Infrastructure.Persistence.Idempotency.IdempotencyRecord", b =>
                {
                    b.Property<string>("Operation")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Key")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("RequestHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nchar(64)")
                        .IsFixedLength();

                    b.Property<Guid>("ResourceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ResponseBody")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StatusCode")
                        .HasColumnType("int");

                    b.HasKey("Operation", "Key");

                    b.HasIndex("CreatedAt");

                    b.ToTable("IdempotencyRecords", (string)null);
                });

            modelBuilder.Entity("DotNetTestMundial.Domain.Entities.Goal", b =>
                {
                    b.HasOne("DotNetTestMundial.Domain.Entities.Match", null)
                        .WithMany("Goals")
                        .HasForeignKey("MatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DotNetTestMundial.Domain.Entities.Player", null)
                        .WithMany()
                        .HasForeignKey("PlayerId", "TeamId")
                        .HasPrincipalKey("Id", "TeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("DotNetTestMundial.Domain.Entities.Match", b =>
                {
                    b.HasOne("DotNetTestMundial.Domain.Entities.Team", null)
                        .WithMany()
                        .HasForeignKey("AwayTeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DotNetTestMundial.Domain.Entities.Team", null)
                        .WithMany()
                        .HasForeignKey("HomeTeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("DotNetTestMundial.Domain.Entities.Player", b =>
                {
                    b.HasOne("DotNetTestMundial.Domain.Entities.Team", null)
                        .WithMany("Players")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("DotNetTestMundial.Domain.Entities.Match", b =>
                {
                    b.Navigation("Goals");
                });

            modelBuilder.Entity("DotNetTestMundial.Domain.Entities.Team", b =>
                {
                    b.Navigation("Players");
                });
#pragma warning restore 612, 618
        }
    }
}
