<Project Sdk="Microsoft.NET.Sdk">

  <!-- Responsabilidad del proyecto: Contiene reglas de negocio sin referencias a otras capas. -->

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
